steps:
  - name: 'registry.hub.docker.com/library/golang'
    args: ['go', 'version']
  - name: 'registry.hub.docker.com/library/golang'
    args: ['go', 'test']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'HelloHTTP', '--trigger-http', '--runtime', 'go113']